# Generated by Django 6.0.5 on 2026-05-25 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="role",
            field=models.CharField(
                choices=[
                    ("WARGA", "Warga"),
                    ("PETUGAS", "Petugas Ronda"),
                    ("RT", "Ketua RT"),
                ],
                default="WARGA",
                max_length=10,
            ),
        ),
    ]
