# Generated by Django 6.0.5 on 2026-05-29 15:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_userprofile_is_verified_userprofile_role"),
    ]

    operations = [
        migrations.CreateModel(
            name="NIKWhitelist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nik", models.CharField(max_length=16, unique=True)),
                ("nama_sesuai", models.CharField(blank=True, max_length=100)),
                ("is_used", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "NIK Whitelist",
                "verbose_name_plural": "NIK Whitelist",
            },
        ),
        migrations.AddField(
            model_name="userprofile",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="userprofile",
            name="nik",
            field=models.CharField(blank=True, max_length=16, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="nama_lengkap",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="no_hp",
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="role",
            field=models.CharField(
                choices=[
                    ("WARGA", "Warga"),
                    ("PETUGAS", "Petugas Ronda"),
                    ("RT", "Pengurus RT"),
                ],
                default="WARGA",
                max_length=10,
            ),
        ),
    ]
