# Generated by Django 6.0.5 on 2026-05-30 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "account",
            "0003_nikwhitelist_userprofile_created_at_userprofile_nik_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="rt",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
