# Generated by Django 6.0.5 on 2026-05-31 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0004_userprofile_rt"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="active_role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("WARGA", "Warga"),
                    ("PETUGAS", "Petugas Ronda"),
                    ("RT", "Pengurus RT"),
                ],
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="alamat",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="foto_kk",
            field=models.ImageField(blank=True, null=True, upload_to="dokumen/kk/"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="foto_ktp",
            field=models.ImageField(blank=True, null=True, upload_to="dokumen/ktp/"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="foto_profil",
            field=models.ImageField(blank=True, null=True, upload_to="profil/"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="jenis_kelamin",
            field=models.CharField(
                blank=True,
                choices=[("L", "Laki-laki"), ("P", "Perempuan")],
                max_length=1,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="pekerjaan",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="rw",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="submission_status",
            field=models.CharField(
                choices=[
                    ("draft", "Belum Dikirim"),
                    ("pending", "Menunggu Verifikasi"),
                    ("verified", "Terverifikasi"),
                ],
                default="draft",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="tanggal_lahir",
            field=models.DateField(blank=True, null=True),
        ),
    ]
