# Generated by Django 6.0.5 on 2026-06-11 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0005_userprofile_active_role_userprofile_alamat_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="nikwhitelist",
            name="rt",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="nikwhitelist",
            name="rw",
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
