# Generated by Django 6.0.5 on 2026-06-03 02:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JadwalRonda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField()),
                ('jam_mulai', models.TimeField()),
                ('jam_selesai', models.TimeField()),
                ('nama_shift', models.CharField(blank=True, choices=[('shift_1', 'Shift Pertama (20:00-22:00)'), ('shift_2', 'Shift Kedua (22:00-00:00)'), ('shift_3', 'Shift Ketiga (00:00-02:00)'), ('shift_4', 'Shift Keempat (02:00-04:00)')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dibuat_oleh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jadwal_dibuat', to=settings.AUTH_USER_MODEL)),
                ('petugas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jadwal_ronda', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Jadwal Ronda',
                'verbose_name_plural': 'Jadwal Ronda',
                'ordering': ['tanggal', 'jam_mulai'],
                'unique_together': {('petugas', 'tanggal', 'jam_mulai')},
            },
        ),
        migrations.CreateModel(
            name='AbsensiShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waktu_absen', models.DateTimeField(auto_now_add=True)),
                ('foto_absen', models.ImageField(blank=True, null=True, upload_to='absensi/foto/')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('akurasi_gps', models.FloatField(blank=True, help_text='Akurasi GPS dalam meter', null=True)),
                ('jarak_dari_pos', models.FloatField(blank=True, help_text='Jarak petugas dari pos ronda saat absen (meter)', null=True)),
                ('catatan', models.TextField(blank=True)),
                ('status_absen', models.CharField(choices=[('hadir', 'Hadir Tepat Waktu'), ('terlambat', 'Terlambat'), ('tidak_hadir', 'Tidak Hadir')], default='hadir', max_length=15)),
                ('status_validasi', models.CharField(choices=[('menunggu', 'Menunggu Validasi RT'), ('valid', 'Valid'), ('ditolak', 'Ditolak')], default='menunggu', max_length=10)),
                ('catatan_rt', models.TextField(blank=True, help_text='Catatan RT saat validasi/tolak')),
                ('divalidasi_at', models.DateTimeField(blank=True, null=True)),
                ('divalidasi_oleh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='absensi_divalidasi', to=settings.AUTH_USER_MODEL)),
                ('jadwal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='absensi', to='patrol.jadwalronda')),
            ],
            options={
                'verbose_name': 'Absensi Shift',
                'verbose_name_plural': 'Absensi Shift',
            },
        ),
    ]
