# Generated by Django 6.0.5 on 2026-06-03 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrol', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='absensishift',
            name='catatan',
        ),
        migrations.RemoveField(
            model_name='absensishift',
            name='catatan_rt',
        ),
        migrations.RemoveField(
            model_name='absensishift',
            name='divalidasi_at',
        ),
        migrations.RemoveField(
            model_name='absensishift',
            name='divalidasi_oleh',
        ),
        migrations.RemoveField(
            model_name='absensishift',
            name='status_validasi',
        ),
        migrations.RemoveField(
            model_name='jadwalronda',
            name='nama_shift',
        ),
        migrations.AlterField(
            model_name='absensishift',
            name='akurasi_gps',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='absensishift',
            name='jarak_dari_pos',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='absensishift',
            name='status_absen',
            field=models.CharField(choices=[('hadir', 'Hadir'), ('terlambat', 'Terlambat'), ('tidak_hadir', 'Tidak Hadir')], default='hadir', max_length=15),
        ),
    ]
