# Generated by Django 6.0.5 on 2026-06-04 17:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrol', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jadwalronda',
            name='blok_area',
        ),
        migrations.RemoveField(
            model_name='jadwalronda',
            name='catatan_rt',
        ),
        migrations.AddField(
            model_name='jadwalronda',
            name='nama_shift',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.RemoveField(
            model_name='jadwalronda',
            name='petugas',
        ),
        migrations.AddField(
            model_name='jadwalronda',
            name='petugas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
