# Generated by Django 6.0.5 on 2026-06-04 17:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrol', '0002_remove_jadwalronda_blok_area_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='jadwalronda',
            name='petugas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jadwal_ronda', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='jadwalronda',
            unique_together={('petugas', 'tanggal', 'jam_mulai')},
        ),
    ]
