# Generated by Django 6.0.5 on 2026-06-12 05:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_rt', '0001_initial'),
        ('patrol', '0003_alter_jadwalronda_petugas_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogPatroli',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('belum', 'Belum Dimulai'), ('berjalan', 'Sedang Berjalan'), ('selesai', 'Selesai')], default='belum', max_length=10)),
                ('waktu_mulai', models.DateTimeField(blank=True, null=True)),
                ('waktu_selesai', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_patroli', to='dashboard_rt.itempatroli')),
                ('jadwal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='log_patroli', to='patrol.jadwalronda')),
                ('petugas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_patroli', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log Patroli',
                'verbose_name_plural': 'Log Patroli',
                'ordering': ['item__urutan'],
                'unique_together': {('item', 'petugas', 'jadwal')},
            },
        ),
    ]
