# Generated by Django 6.0.5 on 2026-06-01 04:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LaporanDarurat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kategori",
                    models.CharField(
                        choices=[
                            ("pencurian", "Pencurian / Perampokan"),
                            ("kebakaran", "Kebakaran / Asap"),
                            ("medis", "Medis Darurat"),
                            ("mencurigakan", "Orang Mencurigakan"),
                        ],
                        max_length=20,
                    ),
                ),
                ("deskripsi", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Menunggu"),
                            ("proses", "Diproses"),
                            ("selesai", "Selesai"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("dibuat", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="laporan_darurat",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-dibuat"],
            },
        ),
    ]
