# Generated by Django 6.0.5 on 2026-06-01 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emergency", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="laporandarurat",
            name="alamat",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="laporandarurat",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="laporandarurat",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
    ]
