# Generated by Django 6.0.5 on 2026-06-01 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emergency", "0002_laporandarurat_alamat_laporandarurat_latitude_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="laporandarurat",
            name="ditangani_oleh",
            field=models.CharField(
                blank=True,
                help_text="Nama petugas atau instansi yang menangani",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="laporandarurat",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Menunggu"),
                    ("diproses", "Diproses"),
                    ("selesai", "Selesai"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
    ]
