# Generated by Django 6.0.5 on 2026-06-04 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patrol', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name="ItemPatroli",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("urutan", models.PositiveSmallIntegerField(default=0)),
                ("deskripsi", models.CharField(max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "jadwal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="item_patroli",
                        to="patrol.jadwalronda",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item Patroli",
                "verbose_name_plural": "Item Patroli",
                "ordering": ["urutan", "created_at"],
            },
        ),
    ]
